use crate::host::error::*;
use crate::host::scene_message::*;

use futures::prelude::*;
use futures::future::{BoxFuture};
use futures::stream::{BoxStream};
use serde::*;

/// Remote callback functions are used to trigger a callback on the remote side of a connection
pub type RemoteCallbackFn<TMessage> = Box<dyn 'static + Send + Sync + Fn(TMessage) -> BoxFuture<'static, ()>>;

///
/// Identifies a serialized resource
///
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
pub enum SerializationId {
    /// Identifies a stream. These values are assigned monotonically, so this reveals information about the state of the guest/host and is likely guessable
    SimpleStream(usize),

    /// Identifies a function callback. These values are assigned monotonically, so this reveals some state for the guest/host and is likely guessable
    SimpleFunction(usize),
}

///
/// The serialization context can be used to pass things like streams and function calls across
/// a serialization boundary. This generally requires some kind of backing protocol (the guest
/// protocol being the main one that's used), as these are effectively ways to generate new
/// connections or cause callbacks in a remote environment.
///
pub trait SerializationContext {
    /// Converts a stream to a serialization ID that can be retrieved by the other side of a connection to read the stream (the stream is cached until the other side drops it)
    fn send_stream<TStream>(&mut self, stream: TStream) -> Result<SerializationId, SceneSendError<TStream>>
    where TStream: 'static + Send + Unpin + Stream<Item=Vec<u8>>;

    /// Creates a receiving stream from a stream ID generated by 'send_stream' on the other side of the connection
    fn receive_stream(&mut self, stream_id: SerializationId) -> Result<BoxStream<'static, Vec<u8>>, SceneSendError<SerializationId>>;

    /// Converts a callback to a serialization ID that can be retrieved by the other side of the connection (the function is cached until the other side drops it)
    fn send_function<TFn, TMessage>(&mut self, callback: TFn) -> Result<SerializationId, SceneSendError<TFn>>
    where 
        TFn:        'static + Send + Fn(TMessage) -> BoxFuture<'static, ()>,
        TMessage:   SceneMessage;

    /// Creates a local function from a serialization ID from the other side of the connection
    fn receive_function<TMessage>(&mut self, callback_id: SerializationId) -> Result<RemoteCallbackFn<TMessage>, SceneSendError<SerializationId>>
    where TMessage: SceneMessage;
}
