use crate::host::error::*;

use futures::future::{BoxFuture};
use futures::stream::{BoxStream};
use serde::*;

/// Remote callback functions are used to trigger a callback on the remote side of a connection
pub type RemoteCallbackFn = Box<dyn 'static + Send + Sync + Fn(Vec<u8>) -> BoxFuture<'static, ()>>;

///
/// Identifies a serialized resource
///
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
pub enum SerializationId {
    /// Identifies a stream. These values are assigned monotonically, so this reveals information about the state of the guest/host and is likely guessable
    SimpleStream(usize),

    /// Identifies a function callback. These values are assigned monotonically, so this reveals some state for the guest/host and is likely guessable
    SimpleFunction(usize),
}

///
/// The serialization context can be used to pass things like streams and function calls across
/// a serialization boundary. This generally requires some kind of backing protocol (the guest
/// protocol being the main one that's used), as these are effectively ways to generate new
/// connections or cause callbacks in a remote environment.
///
pub trait SerializationContext {
    /// Converts a stream to a serialization ID that can be retrieved by the other side of a connection to read the stream (the stream is cached until the other side drops it)
    fn send_stream(&mut self, stream: BoxStream<'static, Vec<u8>>) -> Result<SerializationId, SceneSendError<BoxStream<'static, Vec<u8>>>>;

    /// Creates a receiving stream from a stream ID generated by 'send_stream' on the other side of the connection
    fn receive_stream(&mut self, stream_id: SerializationId) -> Result<BoxStream<'static, Vec<u8>>, SceneSendError<SerializationId>>;

    /// Converts a callback to a serialization ID that can be retrieved by the other side of the connection (the function is cached until the other side drops it)
    fn send_function(&mut self, callback: RemoteCallbackFn) -> Result<SerializationId, SceneSendError<RemoteCallbackFn>>;

    /// Creates a local function from a serialization ID from the other side of the connection
    fn receive_function(&mut self, callback_id: SerializationId) -> Result<RemoteCallbackFn, SceneSendError<SerializationId>>;
}

///
/// Serialization context that has no connection behind it (just returns errors when trying to send or receive streams or functions)
///
#[derive(Debug)]
pub struct DisconnectedSerializationContext;

impl SerializationContext for DisconnectedSerializationContext {
    fn send_stream(&mut self, stream: BoxStream<'static, Vec<u8>>) -> Result<SerializationId, SceneSendError<BoxStream<'static, Vec<u8>>>> {
        Err(SceneSendError::NoConnection(stream))
    }

    fn receive_stream(&mut self, stream_id: SerializationId) -> Result<BoxStream<'static, Vec<u8>>, SceneSendError<SerializationId>> {
        Err(SceneSendError::NoConnection(stream_id))
    }

    fn send_function(&mut self, callback: RemoteCallbackFn) -> Result<SerializationId, SceneSendError<RemoteCallbackFn>> {
        Err(SceneSendError::NoConnection(callback))
    }

    fn receive_function(&mut self, callback_id: SerializationId) -> Result<RemoteCallbackFn, SceneSendError<SerializationId>> {
        Err(SceneSendError::NoConnection(callback_id))
    }
}
