use crate::host::error::*;

use futures::future::{BoxFuture};
use futures::stream::{BoxStream};
use serde::*;

/// Remote callback functions are used to trigger a callback on the remote side of a connection
pub type RemoteCallbackFn = Box<dyn 'static + Send + Sync + Fn(Vec<u8>) -> BoxFuture<'static, ()>>;

///
/// Identifies a serialized resource
///
#[derive(Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Serialize, Deserialize)]
pub enum SerializationId {
    /// Identifies a stream whose source is on this side of the connection
    MyStream(usize),

    /// Idenitifies a stream whose source is on the target side of the connection
    TheirStream(usize),
}

///
/// The serialization context can be used to pass things like streams and function calls across
/// a serialization boundary. This generally requires some kind of backing protocol (the guest
/// protocol being the main one that's used), as these are effectively ways to generate new
/// connections or cause callbacks in a remote environment.
///
pub trait SerializationContext : Send + Sync {
    /// Converts a stream to a serialization ID that can be retrieved by the other side of a connection to read the stream (the stream is cached until the other side drops it)
    fn send_stream(&self, stream: BoxStream<'static, Vec<u8>>) -> Result<SerializationId, SceneSendError<BoxStream<'static, Vec<u8>>>>;

    /// Creates a receiving stream from a stream ID generated by 'send_stream' on the other side of the connection
    fn receive_stream(&self, stream_id: SerializationId) -> Result<BoxStream<'static, Vec<u8>>, SceneSendError<SerializationId>>;

    /// Converts a callback to a serialization ID that can be retrieved by the other side of the connection (the function is cached until the other side drops it)
    fn send_function(&self, callback: RemoteCallbackFn) -> Result<SerializationId, SceneSendError<RemoteCallbackFn>>;

    /// Creates a local function from a serialization ID from the other side of the connection
    fn receive_function(&self, callback_id: SerializationId) -> Result<RemoteCallbackFn, SceneSendError<SerializationId>>;
}

///
/// Serialization context that has no connection behind it (just returns errors when trying to send or receive streams or functions)
///
#[derive(Clone, Debug)]
pub struct DisconnectedSerializationContext;

impl SerializationId {
    ///
    /// Returns the 'opposite' of the current stream (converts 'MyStream' to 'TheirStream' and vice-vera)
    ///
    pub fn invert(&self) -> Self {
        match self {
            Self::MyStream(id)      => Self::TheirStream(*id),
            Self::TheirStream(id)   => Self::MyStream(*id),
        }
    }

    ///
    /// Converts a serialization ID to one that's owned on 'this side' of the connection
    ///
    pub fn to_mine(&self) -> Self {
        match self {
            Self::MyStream(id) | Self::TheirStream(id) => Self::MyStream(*id)
        }
    }

    ///
    /// Converts a serialization ID to one that's owned on the 'other side' of the connection
    ///
    pub fn to_theirs(&self) -> Self {
        match self {
            Self::MyStream(id) | Self::TheirStream(id) => Self::TheirStream(*id)
        }
    }
}

impl SerializationContext for DisconnectedSerializationContext {
    fn send_stream(&self, stream: BoxStream<'static, Vec<u8>>) -> Result<SerializationId, SceneSendError<BoxStream<'static, Vec<u8>>>> {
        Err(SceneSendError::NoConnection(stream))
    }

    fn receive_stream(&self, stream_id: SerializationId) -> Result<BoxStream<'static, Vec<u8>>, SceneSendError<SerializationId>> {
        Err(SceneSendError::NoConnection(stream_id))
    }

    fn send_function(&self, callback: RemoteCallbackFn) -> Result<SerializationId, SceneSendError<RemoteCallbackFn>> {
        Err(SceneSendError::NoConnection(callback))
    }

    fn receive_function(&self, callback_id: SerializationId) -> Result<RemoteCallbackFn, SceneSendError<SerializationId>> {
        Err(SceneSendError::NoConnection(callback_id))
    }
}

impl SerializationContext for Box<dyn SerializationContext> {
    #[inline]
    fn send_stream(&self, stream: BoxStream<'static, Vec<u8>>) -> Result<SerializationId, SceneSendError<BoxStream<'static, Vec<u8>>>> {
        (**self).send_stream(stream)
    }

    #[inline]
    fn receive_stream(&self, stream_id: SerializationId) -> Result<BoxStream<'static, Vec<u8>>, SceneSendError<SerializationId>> {
        (**self).receive_stream(stream_id)
    }

    #[inline]
    fn send_function(&self, callback: RemoteCallbackFn) -> Result<SerializationId, SceneSendError<RemoteCallbackFn>> {
        (**self).send_function(callback)
    }

    #[inline]
    fn receive_function(&self, callback_id: SerializationId) -> Result<RemoteCallbackFn, SceneSendError<SerializationId>> {
        (**self).receive_function(callback_id)
    }
}
