use super::command_response::*;
use super::command_socket::*;
use crate::parser::*;

use flo_scene::*;
use flo_scene::programs::*;

use futures::prelude::*;
use futures::stream::{BoxStream};

use serde::{Deserialize, Serialize};
use serde_json;

use std::fmt::{Debug};

///
/// A string value representing the name of a command sent to a stream
///
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct CommandName(pub String);

///
/// A string value representing the name of a variable to assign
///
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct VariableName(pub String);

///
/// An argument to a command sent to a stream
///
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommandArgument {
    Json(serde_json::Value)
}

///
/// A command parsed from an input stream
///
/// Commands have the format `<CommandName> <Argument>`, where the command name is an identifier and the arguments is a single
/// JSON value (multiple values can be passed by chained together commands using '|' operator)
///
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum CommandRequest {
    /// Runs a command with an argument, generating one or more CommandResponse as a result
    Command     { command: CommandName, argument: ParsedJson },

    /// Generates a JSON CommandResponse from the value
    RawJson     { value: ParsedJson },

    /// Takes the JSON response(s) from a command and passes it to an IO stream generated by the 'to' command
    Pipe        { from: Box<CommandRequest>, to: Box<CommandRequest> },

    /// Sets a variable to the JSON output of a command
    Assign      { variable: VariableName, from: Box<CommandRequest> },

    /// Sends the JSON output of a command to a stream target as a query response
    ForTarget   { target: StreamTarget, request: Box<CommandRequest> },
}

impl SceneMessage for CommandRequest {
    #[inline]
    fn message_type_name() -> String { "flo_scene_pipe::CommandRequest".into() }
}

impl Into<String> for CommandName {
    #[inline]
    fn into(self) -> String {
        self.0
    }
}

impl QueryRequest for CommandRequest {
    type ResponseData = CommandResponse;

    fn with_new_target(self, new_target: StreamTarget) -> Self {
        match self {
            CommandRequest::ForTarget { request, .. } => {
                CommandRequest::ForTarget { target: new_target, request: request }
            }

            other => {
                CommandRequest::ForTarget { target: new_target, request: Box::new(other) }
            }
        }
    }
}

impl CommandRequest {
    ///
    /// Creates a command by parsing a string
    ///
    pub async fn parse(command: &str) -> Result<CommandRequest, CommandParseError> {
        let mut parser      = Parser::new();
        let mut tokenizer   = Tokenizer::new(stream::iter(command.bytes()).ready_chunks(256));

        tokenizer.with_command_matchers();

        command_parse(&mut parser, &mut tokenizer).await?;

        Ok(parser.finish()?)
    }
}

impl Into<String> for VariableName {
    fn into(self) -> String {
        self.0
    }
}

impl<'a> Into<String> for &'a VariableName {
    fn into(self) -> String {
        self.0.clone()
    }
}

///
/// Reads data for the command program socket from an input stream
///
/// Often used with a socket, for example `start_internal_socket_program(&scene, socket_program, read_command_data, write_command_data)`
///
pub fn read_command_data(input: impl 'static + Send + Unpin + Stream<Item=Vec<u8>>) -> impl 'static + Send + Unpin + Stream<Item=CommandData> {
    input.map(|data| CommandData(data))
}

///
/// Converts command data to bytes ready to be sent to a socket stream
///
/// Often used with a socket, for example `start_internal_socket_program(&scene, socket_program, read_command_data, write_command_data)`
///
pub fn write_command_data(input: impl 'static + Send + Unpin + Stream<Item=CommandData>) -> BoxStream<'static, Vec<u8>> {
    input.map(|CommandData(data)| data).boxed()
}
