use serde::*;

///
/// Errors that can be generated by the WASM control program
///
#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum WasmSubprogramError {
    /// An uncategorised error with a description of what went wrong
    Description(String),
}