use serde::*;

///
/// Errors that can be generated by the WASM control program
///
#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum WasmSubprogramError {
    /// An uncategorised error with a description of what went wrong
    Description(String),

    /// The buffer functions are not in the wasm program
    MissingBufferFunctions,

    /// The runtime functions for the requested serialization format were missing
    MissingRuntimeFunctions,
}

impl From<wasmer::WasmError> for WasmSubprogramError {
    fn from(err: wasmer::WasmError) -> Self {
        WasmSubprogramError::Description(format!("{:?}", err))
    }
}

impl From<wasmer::CompileError> for WasmSubprogramError {
    fn from(err: wasmer::CompileError) -> Self {
        WasmSubprogramError::Description(format!("{:?}", err))
    }
}

impl From<wasmer::InstantiationError> for WasmSubprogramError {
    fn from(err: wasmer::InstantiationError) -> Self {
        WasmSubprogramError::Description(format!("{:?}", err))
    }
}
