[package]
name            = "flo_scene_guest"
version         = "0.2.0"
edition         = "2021"
authors         = ["Andrew Hunter"]
license         = "Apache-2.0"
readme          = "../README.md"
repository      = "https://github.com/Logicalshift/flo_scene"
description     = "no_std implementation of the guest protocol for flo_scene for smaller wasm guests"
categories      = [ "concurrency", "data-structures" ]
keywords        = [ "message-queue" ]

[features]
# By default assume we're creating a wasm module which will run on a single thread
default         = [ "one_thread" ]

# Use std after all, protect shared data with shared mutexes
use-std         = [ "postcard/use-std", "futures/std" ]

# If std is not applied, assume that we're running in single-threaded mode
one_thread      = [ "spin" ]

# Adds support for JSON encoding
json            = [ "serde_json" ]

# Allow internal random number generation (for generating UUIDs)
use-random      = [ "uuid/v4" ]

[dependencies]
postcard        = { version = "1.0", features = [ "alloc" ] }
futures         = { version = "0.3", default-features = false, features = [ "alloc" ] }
serde           = { version = "1.0", default-features = false, features = [ "derive" ] }
uuid            = { version = "1.0", default-features = false, features = [ "serde" ] }
spin            = { version = "0.9", default-features = false, optional = true, features = [ "mutex", "spin_mutex" ] }
serde_json      = { version = "1.0", optional = true }
once_cell       = { version = "1.18", default-features = false, features = [ "alloc", "race" ] }

[dev-dependencies]
serde_json      = { version = "1.0" }
