[package]
name            = "flo_scene_nostd"
version         = "0.2.0"
edition         = "2021"
authors         = ["Andrew Hunter"]
license         = "Apache-2.0"
readme          = "README.md"
repository      = "https://github.com/Logicalshift/flo_scene"
description     = "no_std implementation of the guest protocol for flo_scene for smaller wasm guests"
categories      = [ "concurrency", "data-structures" ]
keywords        = [ "message-queue" ]

[dependencies]
postcard        = { version = "1.0" }
futures         = { version = "0.3", default-features = false }
