[workspace]
members     = [
    "buffer_tests",
    "subprogram_test",
]
resolver    = "2"

[profile.release]
lto         = true
opt-level   = 'z'

[patch.crates-io]
flo_scene = { path = "../scene" }
